repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.5
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      # tfsec está deprecado → usar Trivy
      - id: terraform_trivy
        # opcional: suavizar el fallo si solo querés avisos en PRs
        args: [--severity, HIGH,CRITICAL, --exit-code, "0"]
        # ↑ deja el job en verde pero te muestra findings

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.6
    hooks:
      - id: actionlint