apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: { { .Values.namespace } }
spec:
  type: { { .Values.service.type } }
  selector:
    app: app
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
