apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-api
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["app"]
  selector:
    matchLabels:
      app.kubernetes.io/name: app
      app.kubernetes.io/instance: app-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s