name: app-build-deploy (dev)

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/app-build-deploy.yml'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

concurrency:
  group: app-deploy-main
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1
  NS: app

jobs:
  build_push_deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get AWS account ID
        id: acct
        run: echo "id=$(aws sts get-caller-identity --query Account --output text)" >> "$GITHUB_OUTPUT"

      - name: Build & Push images (api & web)
        env:
          SHA: ${{ github.sha }}
          REG: ${{ env.AWS_REGION }}
          ACC: ${{ steps.acct.outputs.id }}
        shell: bash
        run: |
          set -euo pipefail
          API_REPO="${ACC}.dkr.ecr.${REG}.amazonaws.com/app-api"
          WEB_REPO="${ACC}.dkr.ecr.${REG}.amazonaws.com/app-web"

          docker build -t "${API_REPO}:${SHA}" "app/api"
          docker push "${API_REPO}:${SHA}"

          docker build -t "${WEB_REPO}:${SHA}" "app/web"
          docker push "${WEB_REPO}:${SHA}"

          echo "API_IMAGE=${API_REPO}:${SHA}" >> "$GITHUB_ENV"
          echo "WEB_IMAGE=${WEB_REPO}:${SHA}" >> "$GITHUB_ENV"


      - name: Configure AWS creds (OIDC) for kubectl/helm
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::215873709989:role/gha-app-dev
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-app-deploy

      - name: Install kubectl & helm
        shell: bash
        run: |
          set -euo pipefail
          K_VER="$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)"
          curl -sSLo /usr/local/bin/kubectl "https://storage.googleapis.com/kubernetes-release/release/${K_VER}/bin/linux/amd64/kubectl"
          chmod +x /usr/local/bin/kubectl
          curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name dev-eks --region "$AWS_REGION"

      - name: Deploy with Helm (api)
        shell: bash
        run: |
          set -euo pipefail
          REPO="${API_IMAGE%:*}"
          TAG="${API_IMAGE##*:}"
          helm upgrade --install app-api ./app/deploy/chart \
            --namespace "${NS}" --create-namespace \
            -f app/deploy/chart/values-api.yaml \
            --set image.repository="${REPO}" \
            --set image.tag="${TAG}" \
            --set pod.serviceAccountAnnotations."eks\.amazonaws\.com/role-arn"="${{ secrets.IRSA_ROLE_ARN_API }}"

      - name: Deploy with Helm (web)
        shell: bash
        run: |
          set -euo pipefail
          REPO="${WEB_IMAGE%:*}"
          TAG="${WEB_IMAGE##*:}"
          helm upgrade --install app-web ./app/deploy/chart \
            --namespace "${NS}" \
            -f app/deploy/chart/values-web.yaml \
            --set image.repository="${REPO}" \
            --set image.tag="${TAG}"
