# .github/workflows/checks.yml
name: repo-checks

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '**/*.yaml'
      - '**/*.yml'
      - 'app/**'
      - '.pre-commit-config.yaml'
      - '.github/workflows/checks.yml'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Terraform (para terraform_fmt/validate)
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.x

      # TFLint (para terraform_tflint)
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.51.1

      # Trivy (para terraform_trivy)
      - uses: aquasecurity/setup-trivy@v0.2.2

      # Python + pre-commit
      - uses: actions/setup-python@v5
      - name: Install pre-commit
        run: pip install pre-commit

      # (opcional) Aumentar tolerancia a lock del state si tus hooks llaman terraform init
      - name: Run pre-commit on all files
        env:
          # PCT_TFPATH le dice a los hooks dónde está terraform (no suele hacer falta, pero no molesta)
          PCT_TFPATH: terraform
        run: pre-commit run --all-files