name: tf-plan (dev)

on:
  pull_request:
    paths:
      - 'environments/dev/**'
      - 'modules/**'
      - '.github/workflows/tf-plan.yml'

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: tf-plan-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: environments/dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.9.x }

      - name: AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::215873709989:role/gha-terraform-dev
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-tf-plan

      - name: WhoAmI
        run: aws sts get-caller-identity

      - name: Terraform init
        run: terraform init -input=false

      - name: Format & Validate
        run: |
          terraform fmt -check
          terraform validate

      - name: TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init
          tflint

      - name: tfsec (IaC scan)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: environments/dev
          soft_fail: true

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif

      - name: Terraform plan
        run: terraform plan -input=false