name: tf-plan (dev)

on:
  pull_request:
    paths:
      - 'environments/dev/**'
      - 'modules/**'
      - '.github/workflows/**'
  workflow_dispatch: {}

permissions:
  id-token: write   # <- OBLIGATORIO para OIDC
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1   # ajusta región
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.x

      - name: Debug GH context
        run: |
          echo "event=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          echo "repo=${{ github.repository }}"

      - name: Inspect OIDC claims (safe)
        shell: bash
        run: |
          echo "::group::Fetch OIDC token"
          TOK=$(curl -sLS -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" | jq -r '.value')
          echo "::endgroup::"
          SUB=$(echo "$TOK" | cut -d '.' -f2 | base64 -d 2>/dev/null | jq -r .sub)
          AUD=$(echo "$TOK" | cut -d '.' -f2 | base64 -d 2>/dev/null | jq -r .aud)
          echo "oidc.sub=$SUB"
          echo "oidc.aud=$AUD"
          echo "gh.ref=${{ github.ref }}"
          echo "gh.repository=${{ github.repository }}"

      - name: Configure AWS creds via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::215873709989:role/gha-terraform-dev
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-tf-plan

      - name: WhoAmI
        run: aws sts get-caller-identity

      - name: Terraform init/validate/plan
        working-directory: environments/dev
        run: |
          terraform init -upgrade
          terraform fmt -check
          terraform validate
          terraform plan -input=false -out=tfplan